name: "dl_torch_mae_cnn"

feature_definition:
  use_norm_features: False

data_loader:
  batch_size: 512
  generate_by: "across_dataset"
  mixup: "across"
  mixup_alpha: 0.2

model_params:
  arch: "1dCNN"
  input_dim: 2
  conv_shapes: [8, 8, 8]
  embedding_size: 16
  flag_y_vector: True
  max_masked_modalities: 2

training_params:
  optimizer: "Adam"
  scheduler: "cosine_restarts"
  learning_rate: 0.001
  cos_annealing_step: 20
  cos_annealing_decay: 0.95
  cos_annealing_alpha: 0.01
  cos_annealing_t_mul: 2.0
  epochs: 200
  steps_per_epoch: 100
  pretrain_patience: 10
  patience: 10
  grad_clip: 0.0
  best_epoch_strategy: "direct"
  verbose: 0
  skip_training: False
